parameters:
#    api_authorized_grant.example.class: API\AuthorizedGrantBundle\Example

services:
  api.logger.mobile:
    class: API\AuthorizedGrantBundle\Monolog\MobileLogger
    arguments: [@logger]
    tags:
      - { name: monolog.logger, channel: mobile }
  api.logger.fileupload:
      class: API\AuthorizedGrantBundle\Monolog\MobileLogger
      arguments: [@logger]
      tags:
        - { name: monolog.logger, channel: fileupload }
  api.logger.insertdata:
      class: API\AuthorizedGrantBundle\Monolog\MobileLogger
      arguments: [@logger]
      tags:
        - { name: monolog.logger, channel: insertdata }
