imports:
  - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
  channels: ['mobile', 'fileupload', 'insertdata']
  handlers:
    main:
      type:         fingers_crossed
      action_level: error
      handler:      nested
    nested:
      type:  stream
      path:  "%kernel.logs_dir%/%kernel.environment%.log"
      level: debug
    console:
      type:  console
    mobile:
      type: stream
      path: "%kernel.logs_dir%/mobile_app_%kernel.environment%.log"
      level: info
      channels: [mobile]
    fileupload:
      type: stream
      path: "%kernel.logs_dir%/image_upload_%kernel.environment%.log"
      level: info
      channels: [fileupload]
    insertdata:
      type: stream
      path: "%kernel.logs_dir%/insert_data_%kernel.environment%.log"
      level: info
      channels: [insertdata]
