parameters:
#    api_client_grant.example.class: API\ClientGrantBundle\Example

services:
#    api_client_grant.example:
#        class: %api_client_grant.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
